changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: "💥 Breaking Changes"
      labels:
        - breaking-change
        - breaking
    - title: "✨ New Features"
      labels:
        - enhancement
        - feature
    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix
    - title: "📚 Documentation"
      labels:
        - documentation
        - docs
    - title: "🧰 Maintenance"
      labels:
        - dependencies
        - maintenance
        - chore
        - ci
    - title: "🔧 Other Changes"
      labels:
        - "*"
